### ISSUE TITLE
home page: center text and image

### ISSUE THREAD

**Issue by Sdbns** [WPRN/website#21]
On the home page the text is slightly off-centre to the left in relation to planet earth. 
Could the text be refocused? Or enlarge the frame containing the text? 

<img width="1061" alt="HOME PAGE WPRN" src="https://user-images.githubusercontent.com/64425631/81209002-30a04200-8fd0-11ea-98a9-14c541ef9878.png">

**Comment by Billybobbonnet** [comment]
Fair point. The picture is not centered, that's why. We'll remake the whole splash approach and transition into a more usual menu. Since I already spent a lot on time on this to implement the many changes suggested, I'll leave it as is for the time being. I'll link this ticket in the next menu ticket.

Thank you :sweat_smile:
